### ISSUE TITLE
npm install error: Pre-built binaries not found for node-hid@0.5.2 and node@7.4.0

### ISSUE THREAD

**Issue by sergy8612** [stevelacy/msi-keyboard-gui#23]
I followed your instructions to install from development (the pre-built binaries I haven't got to work)

`$ git clone https://github.com/stevelacy/msi-keyboard-gui
$ cd msi-keyboard-gui
$ npm install
`
And this is what I get after npm install:

`root@sergio-GE72-6QD:/home/sergio/msi-keyboard-gui# npm install
npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-hid@0.5.2 install /home/sergio/msi-keyboard-gui/node_modules/node-hid
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.2/HID-v0.5.2-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.2 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/sergio/msi-keyboard-gui/node_modules/node-hid/.node-gyp"
make: entering to directory '/home/sergio/msi-keyboard-gui/node_modules/node-hid/build'
make: *** no rule to make target '../.node-gyp/7.4.0/include/node/common.gypi', necessary for 'Makefile'.  Stop.
make: exiting directory '/home/sergio/msi-keyboard-gui/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sergio/msi-keyboard-gui/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-57-generic
gyp ERR! command "/usr/bin/nodejs" "/home/sergio/msi-keyboard-gui/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release/HID.node" "--module_name=HID" "--module_path=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release"
gyp ERR! cwd /home/sergio/msi-keyboard-gui/node_modules/node-hid
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/sergio/msi-keyboard-gui/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release/HID.node --module_name=HID --module_path=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/sergio/msi-keyboard-gui/node_modules/node-hid/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-57-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/sergio/msi-keyboard-gui/node_modules/node-hid/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/sergio/msi-keyboard-gui/node_modules/node-hid
node-pre-gyp ERR! node -v v7.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/sergio/msi-keyboard-gui/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release/HID.node --module_name=HID --module_path=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release' (1)
msi-keyboard-gui@0.1.2 /home/sergio/msi-keyboard-gui
├── babel@6.5.2 
├─┬ babel-preset-es2015@6.18.0 
│ ├── babel-plugin-check-es2015-constants@6.8.0 
│ ├── babel-plugin-transform-es2015-arrow-functions@6.8.0 
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.8.0 
│ ├─┬ babel-plugin-transform-es2015-block-scoping@6.21.0 
│ │ ├── babel-template@6.16.0 
│ │ ├─┬ babel-traverse@6.21.0 
│ │ │ └── globals@9.14.0 
│ │ └─┬ babel-types@6.21.0 
│ │   ├── esutils@2.0.2 
│ │   └── to-fast-properties@1.0.2 
│ ├─┬ babel-plugin-transform-es2015-classes@6.18.0 
│ │ ├── babel-helper-define-map@6.18.0 
│ │ ├── babel-helper-function-name@6.18.0 
│ │ ├── babel-helper-optimise-call-expression@6.18.0 
│ │ ├── babel-helper-replace-supers@6.18.0 
│ │ └── babel-messages@6.8.0 
│ ├── babel-plugin-transform-es2015-computed-properties@6.8.0 
│ ├── babel-plugin-transform-es2015-destructuring@6.19.0 
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.8.0 
│ ├── babel-plugin-transform-es2015-for-of@6.18.0 
│ ├── babel-plugin-transform-es2015-function-name@6.9.0 
│ ├── babel-plugin-transform-es2015-literals@6.8.0 
│ ├── babel-plugin-transform-es2015-modules-amd@6.18.0 
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.18.0 
│ │ └── babel-plugin-transform-strict-mode@6.18.0 
│ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.19.0 
│ │ └── babel-helper-hoist-variables@6.18.0 
│ ├── babel-plugin-transform-es2015-modules-umd@6.18.0 
│ ├── babel-plugin-transform-es2015-object-super@6.8.0 
│ ├─┬ babel-plugin-transform-es2015-parameters@6.21.0 
│ │ ├── babel-helper-call-delegate@6.18.0 
│ │ └── babel-helper-get-function-arity@6.18.0 
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.18.0 
│ ├── babel-plugin-transform-es2015-spread@6.8.0 
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.8.0 
│ │ └── babel-helper-regex@6.18.0 
│ ├── babel-plugin-transform-es2015-template-literals@6.8.0 
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.18.0 
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.11.0 
│ │ └─┬ regexpu-core@2.0.0 
│ │   ├── regenerate@1.3.2 
│ │   ├── regjsgen@0.2.0 
│ │   └─┬ regjsparser@0.1.5 
│ │     └── jsesc@0.5.0 
│ └─┬ babel-plugin-transform-regenerator@6.21.0 
│   └── regenerator-transform@0.9.8 
├─┬ babel-preset-react@6.16.0 
│ ├── babel-plugin-syntax-flow@6.18.0 
│ ├── babel-plugin-syntax-jsx@6.18.0 
│ ├── babel-plugin-transform-flow-strip-types@6.21.0 
│ ├── babel-plugin-transform-react-display-name@6.8.0 
│ ├─┬ babel-plugin-transform-react-jsx@6.8.0 
│ │ └── babel-helper-builder-react-jsx@6.21.1 
│ ├── babel-plugin-transform-react-jsx-self@6.11.0 
│ └── babel-plugin-transform-react-jsx-source@6.9.0 
├─┬ babel-register@6.18.0 
│ ├─┬ babel-core@6.21.0 
│ │ ├── babel-code-frame@6.20.0 
│ │ ├─┬ babel-generator@6.21.0 
│ │ │ ├─┬ detect-indent@4.0.0 
│ │ │ │ └─┬ repeating@2.0.1 
│ │ │ │   └── is-finite@1.0.2 
│ │ │ └── jsesc@1.3.0 
│ │ ├── babel-helpers@6.16.0 
│ │ ├── babylon@6.14.1 
│ │ ├── convert-source-map@1.3.0 
│ │ ├── json5@0.5.1 
│ │ ├─┬ minimatch@3.0.3 
│ │ │ └─┬ brace-expansion@1.1.6 
│ │ │   ├── balanced-match@0.4.2 
│ │ │   └── concat-map@0.0.1 
│ │ ├── path-is-absolute@1.0.1 
│ │ ├── private@0.1.6 
│ │ ├── slash@1.0.0 
│ │ └── source-map@0.5.6 
│ ├─┬ babel-runtime@6.20.0 
│ │ └── regenerator-runtime@0.10.1 
│ ├── core-js@2.4.1 
│ ├─┬ home-or-tmp@2.0.0 
│ │ ├── os-homedir@1.0.2 
│ │ └── os-tmpdir@1.0.2 
│ ├── lodash@4.17.4 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ └── source-map-support@0.4.8 
├── classnames@2.2.5 
├─┬ electron-debug@1.1.0 
│ ├── electron-is-dev@0.1.2 
│ └── electron-localshortcut@0.6.1 
├─┬ electron-packager@8.4.0 
│ ├─┬ asar@0.12.4 
│ │ ├── chromium-pickle-js@0.2.0 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├── cuint@0.2.2 
│ │ ├─┬ glob@6.0.4 
│ │ │ ├─┬ inflight@1.0.6 
│ │ │ │ └── wrappy@1.0.2 
│ │ │ ├── inherits@2.0.3 
│ │ │ └── once@1.4.0 
│ │ ├─┬ mksnapshot@0.3.0 
│ │ │ ├─┬ decompress-zip@0.3.0 
│ │ │ │ ├─┬ binary@0.3.0 
│ │ │ │ │ ├── buffers@0.1.1 
│ │ │ │ │ └─┬ chainsaw@0.1.0 
│ │ │ │ │   └── traverse@0.3.9 
│ │ │ │ ├── mkpath@0.1.0 
│ │ │ │ ├── q@1.4.1 
│ │ │ │ ├─┬ readable-stream@1.1.14 
│ │ │ │ │ └── isarray@0.0.1 
│ │ │ │ └─┬ touch@0.0.3 
│ │ │ │   └── nopt@1.0.10 
│ │ │ └── fs-extra@0.26.7 
│ │ └── tmp@0.0.28 
│ ├─┬ debug@2.6.0 
│ │ └── ms@0.7.2 
│ ├─┬ electron-download@3.2.0 
│ │ ├── fs-extra@0.30.0 
│ │ ├── home-path@1.0.3 
│ │ ├── minimist@1.2.0 
│ │ ├─┬ nugget@2.0.1 
│ │ │ ├── minimist@1.2.0 
│ │ │ ├─┬ pretty-bytes@1.0.4 
│ │ │ │ ├── get-stdin@4.0.1 
│ │ │ │ └─┬ meow@3.7.0 
│ │ │ │   ├── camelcase-keys@2.1.0 
│ │ │ │   ├─┬ loud-rejection@1.6.0 
│ │ │ │   │ └─┬ currently-unhandled@0.4.1 
│ │ │ │   │   └── array-find-index@1.0.2 
│ │ │ │   ├── map-obj@1.0.1 
│ │ │ │   ├── minimist@1.2.0 
│ │ │ │   ├─┬ read-pkg-up@1.0.1 
│ │ │ │   │ ├── find-up@1.1.2 
│ │ │ │   │ └─┬ read-pkg@1.1.0 
│ │ │ │   │   ├─┬ load-json-file@1.1.0 
│ │ │ │   │   │ └─┬ strip-bom@2.0.0 
│ │ │ │   │   │   └── is-utf8@0.2.1 
│ │ │ │   │   └── path-type@1.1.0 
│ │ │ │   ├─┬ redent@1.0.0 
│ │ │ │   │ ├── indent-string@2.1.0 
│ │ │ │   │ └── strip-indent@1.0.1 
│ │ │ │   └── trim-newlines@1.0.0 
│ │ │ ├─┬ progress-stream@1.2.0 
│ │ │ │ ├── speedometer@0.1.4 
│ │ │ │ └─┬ through2@0.2.3 
│ │ │ │   └─┬ xtend@2.1.2 
│ │ │ │     └── object-keys@0.4.0 
│ │ │ ├── single-line-log@1.1.2 
│ │ │ └── throttleit@0.0.2 
│ │ ├─┬ path-exists@2.1.0 
│ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │   └── pinkie@2.0.4 
│ │ ├─┬ rc@1.1.6 
│ │ │ ├── deep-extend@0.4.1 
│ │ │ ├── ini@1.3.4 
│ │ │ ├── minimist@1.2.0 
│ │ │ └── strip-json-comments@1.0.4 
│ │ └─┬ sumchecker@1.3.0 
│ │   └── es6-promise@4.0.5 
│ ├─┬ electron-osx-sign@0.4.2 
│ │ ├── bluebird@3.4.7 
│ │ ├── compare-version@0.1.2 
│ │ ├── isbinaryfile@3.0.2 
│ │ ├── minimist@1.2.0 
│ │ └─┬ tempfile@1.1.1 
│ │   └── uuid@2.0.3 
│ ├─┬ extract-zip@1.6.0 
│ │ ├─┬ concat-stream@1.5.0 
│ │ │ ├─┬ readable-stream@2.0.6 
│ │ │ │ ├── core-util-is@1.0.2 
│ │ │ │ ├── isarray@1.0.0 
│ │ │ │ ├── process-nextick-args@1.0.7 
│ │ │ │ ├── string_decoder@0.10.31 
│ │ │ │ └── util-deprecate@1.0.2 
│ │ │ └── typedarray@0.0.6 
│ │ ├── debug@0.7.4 
│ │ ├── mkdirp@0.5.0 
│ │ └─┬ yauzl@2.4.1 
│ │   └─┬ fd-slicer@1.0.1 
│ │     └── pend@1.2.0 
│ ├─┬ fs-extra@1.0.0 
│ │ ├── graceful-fs@4.1.11 
│ │ ├── jsonfile@2.4.0 
│ │ └── klaw@1.3.1 
│ ├─┬ get-package-info@1.0.0 
│ │ ├── bluebird@3.4.7 
│ │ ├── lodash.get@4.4.2 
│ │ └─┬ read-pkg-up@2.0.0 
│ │   ├─┬ find-up@2.1.0 
│ │   │ └─┬ locate-path@2.0.0 
│ │   │   ├─┬ p-locate@2.0.0 
│ │   │   │ └── p-limit@1.1.0 
│ │   │   └── path-exists@3.0.0 
│ │   └─┬ read-pkg@2.0.0 
│ │     ├─┬ load-json-file@2.0.0 
│ │     │ ├─┬ parse-json@2.2.0 
│ │     │ │ └─┬ error-ex@1.3.0 
│ │     │ │   └── is-arrayish@0.2.1 
│ │     │ ├── pify@2.3.0 
│ │     │ └── strip-bom@3.0.0 
│ │     ├─┬ normalize-package-data@2.3.5 
│ │     │ ├── hosted-git-info@2.1.5 
│ │     │ ├─┬ is-builtin-module@1.0.0 
│ │     │ │ └── builtin-modules@1.1.1 
│ │     │ └─┬ validate-npm-package-license@3.0.1 
│ │     │   ├─┬ spdx-correct@1.0.2 
│ │     │   │ └── spdx-license-ids@1.2.2 
│ │     │   └── spdx-expression-parse@1.0.4 
│ │     └── path-type@2.0.0 
│ ├── minimist@1.2.0 
│ ├─┬ plist@2.0.1 
│ │ ├── base64-js@1.1.2 
│ │ ├── xmlbuilder@8.2.2 
│ │ └── xmldom@0.1.27 
│ ├── rcedit@0.7.0 
│ ├── resolve@1.2.0 
│ ├── run-series@1.1.4 
│ ├─┬ sanitize-filename@1.6.1 
│ │ └─┬ truncate-utf8-bytes@1.0.2 
│ │   └── utf8-byte-length@1.0.4 
│ └── semver@5.3.0 
├── electron-prebuilt@1.4.13 
├─┬ electron-rebuild@1.5.5 
│ ├─┬ babel-runtime@6.18.0 
│ │ └── regenerator-runtime@0.9.6 
│ ├── colors@1.1.2 
│ ├─┬ fs-promise@1.0.0 
│ │ ├── any-promise@1.3.0 
│ │ ├── mz@2.6.0 
│ │ └─┬ thenify-all@1.6.0 
│ │   └── thenify@3.2.1 
│ ├── node-abi@1.0.3 
│ ├─┬ node-gyp@3.4.0 
│ │ ├── fstream@1.0.10 
│ │ ├─┬ glob@7.1.1 
│ │ │ └── fs.realpath@1.0.0 
│ │ ├─┬ nopt@3.0.6 
│ │ │ └── abbrev@1.0.9 
│ │ ├─┬ npmlog@3.1.2 
│ │ │ ├─┬ are-we-there-yet@1.1.2 
│ │ │ │ └── delegates@1.0.0 
│ │ │ ├── console-control-strings@1.1.0 
│ │ │ ├─┬ gauge@2.6.0 
│ │ │ │ ├── aproba@1.0.4 
│ │ │ │ ├── has-color@0.1.7 
│ │ │ │ ├── has-unicode@2.0.1 
│ │ │ │ ├── signal-exit@3.0.2 
│ │ │ │ └── wide-align@1.1.0 
│ │ │ └── set-blocking@2.0.0 
│ │ ├── osenv@0.1.4 
│ │ ├─┬ path-array@1.0.1 
│ │ │ └─┬ array-index@1.0.0 
│ │ │   └─┬ es6-symbol@3.1.0 
│ │ │     ├── d@0.1.1 
│ │ │     └─┬ es5-ext@0.10.12 
│ │ │       └── es6-iterator@2.0.0 
│ │ ├─┬ request@2.55.0 
│ │ │ ├── aws-sign2@0.5.0 
│ │ │ ├─┬ bl@0.9.5 
│ │ │ │ └── readable-stream@1.0.34 
│ │ │ ├── caseless@0.9.0 
│ │ │ ├─┬ combined-stream@0.0.7 
│ │ │ │ └── delayed-stream@0.0.5 
│ │ │ ├── forever-agent@0.6.1 
│ │ │ ├─┬ form-data@0.2.0 
│ │ │ │ └── async@0.9.2 
│ │ │ ├─┬ har-validator@1.8.0 
│ │ │ │ ├── bluebird@2.11.0 
│ │ │ │ └─┬ is-my-json-valid@2.15.0 
│ │ │ │   ├── generate-function@2.0.0 
│ │ │ │   ├─┬ generate-object-property@1.2.0 
│ │ │ │   │ └── is-property@1.0.2 
│ │ │ │   ├── jsonpointer@4.0.1 
│ │ │ │   └── xtend@4.0.1 
│ │ │ ├─┬ hawk@2.3.1 
│ │ │ │ ├── boom@2.10.1 
│ │ │ │ ├── cryptiles@2.0.5 
│ │ │ │ ├── hoek@2.16.3 
│ │ │ │ └── sntp@1.0.9 
│ │ │ ├─┬ http-signature@0.10.1 
│ │ │ │ ├── asn1@0.1.11 
│ │ │ │ ├── assert-plus@0.1.5 
│ │ │ │ └── ctype@0.5.3 
│ │ │ ├── isstream@0.1.2 
│ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ ├─┬ mime-types@2.0.14 
│ │ │ │ └── mime-db@1.12.0 
│ │ │ ├── node-uuid@1.4.7 
│ │ │ ├── oauth-sign@0.6.0 
│ │ │ ├── qs@2.4.2 
│ │ │ ├── stringstream@0.0.5 
│ │ │ ├─┬ tough-cookie@2.3.2 
│ │ │ │ └── punycode@1.4.1 
│ │ │ └── tunnel-agent@0.4.3 
│ │ ├─┬ tar@2.2.1 
│ │ │ └── block-stream@0.0.9 
│ │ └─┬ which@1.2.12 
│ │   └── isexe@1.1.2 
│ ├─┬ ora@0.3.0 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.0.0 
│ │ │ ├── strip-ansi@3.0.1 
│ │ │ └── supports-color@2.0.0 
│ │ ├─┬ cli-cursor@1.0.2 
│ │ │ └─┬ restore-cursor@1.0.1 
│ │ │   ├── exit-hook@1.1.1 
│ │ │   └── onetime@1.1.0 
│ │ ├── cli-spinners@0.2.0 
│ │ └── log-symbols@1.0.2 
│ ├── rimraf@2.5.4 
│ ├─┬ spawn-rx@2.0.8 
│ │ └─┬ rxjs@5.0.2 
│ │   └── symbol-observable@1.0.4 
│ └─┬ yargs@3.32.0 
│   ├── camelcase@2.1.1 
│   ├─┬ cliui@3.2.0 
│   │ └── wrap-ansi@2.1.0 
│   ├── decamelize@1.2.0 
│   ├─┬ os-locale@1.4.0 
│   │ └─┬ lcid@1.0.0 
│   │   └── invert-kv@1.0.0 
│   ├─┬ string-width@1.0.2 
│   │ ├── code-point-at@1.1.0 
│   │ └─┬ is-fullwidth-code-point@1.0.0 
│   │   └── number-is-nan@1.0.1 
│   ├── window-size@0.1.4 
│   └── y18n@3.2.1 
├─┬ react@15.4.1 
│ ├─┬ fbjs@0.8.8 
│ │ ├── core-js@1.2.7 
│ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ ├─┬ node-fetch@1.6.3 
│ │ │ │ ├─┬ encoding@0.1.12 
│ │ │ │ │ └── iconv-lite@0.4.15 
│ │ │ │ └── is-stream@1.1.0 
│ │ │ └── whatwg-fetch@2.0.1 
│ │ ├─┬ promise@7.1.1 
│ │ │ └── asap@2.0.5 
│ │ ├── setimmediate@1.0.5 
│ │ └── ua-parser-js@0.7.12 
│ ├─┬ loose-envify@1.3.0 
│ │ └── js-tokens@2.0.0 
│ └── object-assign@4.1.0 
├── react-dom@15.4.1 
└─┬ react-router@2.8.1 
  ├─┬ history@2.1.2 
  │ ├── deep-equal@1.0.1 
  │ ├─┬ query-string@3.0.3 
  │ │ └── strict-uri-encode@1.1.0 
  │ └── warning@2.1.0 
  ├── hoist-non-react-statics@1.2.0 
  ├── invariant@2.2.2 
  └── warning@3.0.0 

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.5.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-hid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sergio/msi-keyboard-gui/npm-debug.log
`
I attach npm-debug log file if it can help:

[npm-debug.log.txt](https://github.com/stevelacy/msi-keyboard-gui/files/688521/npm-debug.log.txt)

I have npm version 4.0.5 and nodejs 7.4.0 and ubuntu 16.04 LTS
root@sergio-GE72-6QD:/home/sergio/msi-keyboard-gui# lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

and libusb-dev and libusb-1.0-0-dev installed

Thanks for your help,

regards

**Comment by stevelacy** [comment]
```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/sergio/msi-keyboard-gui/node_modules/node-hid/.node-gyp"
make: entering to directory '/home/sergio/msi-keyboard-gui/node_modules/node-hid/build'
make: *** no rule to make target '../.node-gyp/7.4.0/include/node/common.gypi', necessary for 'Makefile'. Stop.
```
This seems odd, it is trying to install as root. Can you use node v6?

**Comment by stephenlacy** [comment]
I just pushed changes to the build steps.
Could you do this:
```
git pull
rm -rf node_modules
npm install
sudo npm start
```

**Comment by stephenlacy** [comment]
Just published a release: https://github.com/stevelacy/msi-keyboard-gui/releases/tag/0.1.3
Can you confirm that the binary does run correctly, and if not the errors it produces?
Thanks

**Comment by sergy8612** [comment]
Hi, I tried as you told me, but the problem persists. I don't know why node-hid is giving such problems. Maybe should I downgrade nodejs to 6.x ? 

I'm using root to not have permission-related problems. 

root@sergio-GE72-6QD:/home/sergio/msi-keyboard-gui# git pull
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 15 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.
De https://github.com/stevelacy/msi-keyboard-gui
   fc47d0e..77ecb23  master     -> origin/master
 * [new tag]         0.1.3      -> 0.1.3
Updating fc47d0e..77ecb23
Fast-forward
 README.md    |  4 ++--
 index.js     |  2 +-
 package.json | 26 +++++++++++++-------------
 src/index.js |  2 --
 4 files changed, 16 insertions(+), 18 deletions(-)
root@sergio-GE72-6QD:/home/sergio/msi-keyboard-gui# ls
assets    LICENSE       npm-debug.log      package.json  src
index.js  node_modules  npm-debug.log.txt  README.md     SUPPORTED.md
root@sergio-GE72-6QD:/home/sergio/msi-keyboard-gui# rm -fr node_modules
root@sergio-GE72-6QD:/home/sergio/msi-keyboard-gui# npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> node-hid@0.5.2 install /home/sergio/msi-keyboard-gui/node_modules/node-hid
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.2/HID-v0.5.2-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.2 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/sergio/msi-keyboard-gui/node_modules/node-hid/.node-gyp"
make: entering directory '/home/sergio/msi-keyboard-gui/node_modules/node-hid/build'
make: *** No rule to make target '../.node-gyp/7.4.0/include/node/common.gypi', necessary for 'Makefile'.  Stop.
make: exiting directory '/home/sergio/msi-keyboard-gui/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sergio/msi-keyboard-gui/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-57-generic
gyp ERR! command "/usr/bin/nodejs" "/home/sergio/msi-keyboard-gui/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release/HID.node" "--module_name=HID" "--module_path=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release"
gyp ERR! cwd /home/sergio/msi-keyboard-gui/node_modules/node-hid
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/sergio/msi-keyboard-gui/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release/HID.node --module_name=HID --module_path=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/sergio/msi-keyboard-gui/node_modules/node-hid/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-57-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/sergio/msi-keyboard-gui/node_modules/node-hid/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/sergio/msi-keyboard-gui/node_modules/node-hid
node-pre-gyp ERR! node -v v7.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/sergio/msi-keyboard-gui/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release/HID.node --module_name=HID --module_path=/home/sergio/msi-keyboard-gui/node_modules/node-hid/build/HID/Release' (1)
msi-keyboard-gui@0.1.3 /home/sergio/msi-keyboard-gui
..... 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.5.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-hid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sergio/msi-keyboard-gui/npm-debug.log
[npm-debug.log.txt](https://github.com/stevelacy/msi-keyboard-gui/files/697348/npm-debug.log.txt)

**Comment by stephenlacy** [comment]
Did you run the binary? That does not need to be installed

**Comment by sergy8612** [comment]
Yes! I just tried running the binary.

And it works well!!!

Thank you very much!!



2017-01-10 22:16 GMT+01:00 Steve Lacy <notifications@github.com>:
